language: ruby
rvm:
  - 2.6.0

before_install:
  - gem update --system
  - gem install bundler
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - nvm install 10.15.3
  - npm i -g dat

before_script:
  - dat clone $DAT_HASH ./_site --exit
  - bundle exec jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - DAT_HASH="dat://b568db0b4d348f4ac3825b199fd89f7808dbcc88cf4a8047045f8995aa2e25ad/"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler

script: travis_retry bundle exec htmlproofer --check-html --allow-hash-href ./_site

notifications:
  email: false
