language: ruby
rvm:
- 2.6.0
before_install:
- gem update --system
- gem install bundler
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
- nvm install 10.16.0
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: NcWf78PRWriGDNiCWyz+Fqq6o4MnsB6kDENZyWZpUy9vDcF/Vq1363p/S01LUgruTHqfNRgJ9ej52p1A3wed9oNc/2kb/Zoc9wS9N/kmpgBl8Wmen0G8VfAFOQlX0tKKQbZIY3XIkVVt7ZhpLzqMeZbdCLIj2hz3Lj4GMBmNOOYNnXnHCM9vfCXwmGIHCe2ef6h//0NjC+lur43Fav5wb/c0NgCeEUHX3QCjZjW6ZK4T7ONya85V27ptoDeIUwqhkExC/v62y+o8RewLjstY3P7ElOBsz9tuv6IpFjAH2wRuwnyp3+KnQ3sXRkgYGw6sYI1gEbGmrQ63wKMn7itu9iyw4zD35ypiZjjAqbiQZyuahUJcIppKEl2E5TnfDC5rlk6b1fMz6M3hiJVX1K4UVYWUGaSjbUw2zFHwWTlaBRTFt3/F5mcOtagdbK4olsnbP5UH13o8Z2U+P0S+T7jzwqFJIH/9kzas5oi9e3ik06PIPPNpEGD8AIwhQ6gTvan+gEhhbqgPJMjQIMEb+WB2IAX3daF7wzZNqPBjkZRLeXPX3sKnb52eLA5KghzMoqV4enLuxpkpPR8yg0heipz/BqRxw7eu/SOYby/c7VlBgexTFxa+voGEECZINgB6UPQrhdHdcZSA3hDsMu8g+IOiQDAu/CmasR/xKwJzGo/cgmo=
cache:
  bundler: true
  directories:
  - node_modules

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - bundle exec jekyll build
        - travis_retry bundle exec htmlproofer --check-html --allow-hash-href --internal_domains "/www.ournetworks.ca/,/ournetworks.ca/" ./_site
    - stage: deploy
      name: "Deploy to ournetworks.ca"
      script: bundle exec jekyll build
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "Deployed"
    - name: "Deploy to Dat"
      script:
        - npm i -g dat
        - dat $(head -n 1 .well-known/dat) ./_site --exit
        - bundle exec jekyll build
        - cd _site
        - echo $DATKEY | dat keys import
        - travis_wait 1 dat sync &> /dev/null || travis_terminate 0
    - name: "Deploy to IPFS"
      script:
        - bundle exec jekyll build
        - npm i -g ipfs-deploy garrying/make-relative
        - cd _site
        - make-relative https://ournetworks.ca
        - ipd . -O -C

notifications:
  email: false
